### Create a Numpy array of size 4 x 5.

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])
arr1 = np.array([arr, arr, arr, arr])
print(arr1)

a = np.empty((4,5))
print(a)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[4.68959269e-310 4.68959426e-310 4.68959426e-310 4.68959426e-310
  4.68959426e-310]
 [4.68959426e-310 4.68959426e-310 4.68959426e-310 4.68959426e-310
  4.68959426e-310]
 [4.68959426e-310 4.68959426e-310 4.68959426e-310 4.68959426e-310
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]]


### Randomly initialize the array.

In [ ]:
arr_random = np.random.rand(4,5)

print(arr_random)

[[0.38753332 0.6802428  0.93540491 0.59133094 0.18178683]
 [0.98908752 0.1662302  0.30975769 0.91522891 0.77491682]
 [0.69565722 0.77674356 0.04169356 0.19854752 0.12403232]
 [0.02658721 0.97765134 0.98241838 0.48287852 0.8971083 ]]


### Get the Determinant and Transpose of the Matrix that you created.


In [ ]:
print("Array Before Transpose: \n",arr1)

arr_Transpose = arr1.T
print("Array After Transpose: ")
print(arr_Transpose)

print("Array Determinant")

arr_Det = np.array([[7,8],[5,4]])

print(np.linalg.det(arr_Det))

# print(arr_Det.shape)
# print(arr_Det)

Array Before Transpose: 
 [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
Array After Transpose: 
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]]
Array Determinant
-11.999999999999995



### Create another matrix of size 5 x 4 and randomly initialize it.
### Perform Matrix multiplication.

In [ ]:
arr2 = np.random.rand(4,5)
print("Array 1: \n",arr1)
print("Array 2: \n",arr2)
arr_mult = np.multiply(arr1,arr2)
print("Multiplicayion Array: \n",arr_mult)

Array 1: 
 [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
Array 2: 
 [[0.38684005 0.76060458 0.69777394 0.02311452 0.99480183]
 [0.09485213 0.45286864 0.9801529  0.51930024 0.00748092]
 [0.81084483 0.40374051 0.42308507 0.3772264  0.93751731]
 [0.27656417 0.07520774 0.08881119 0.78621461 0.19403119]]
Multiplicayion Array: 
 [[0.38684005 1.52120915 2.09332183 0.09245808 4.97400917]
 [0.09485213 0.90573728 2.94045869 2.07720097 0.03740461]
 [0.81084483 0.80748103 1.2692552  1.50890559 4.68758653]
 [0.27656417 0.15041547 0.26643356 3.14485845 0.97015593]]


### Find mean, median of the numpy array created.

In [ ]:
arr3 = np.array([[4,5,6],[1,5,9],[7,2,9]])
print(arr3)
mean1 = np.mean(arr3)
print("Mean is: ",mean1)
median1 = np.median(arr3)
print("Median is: ",median1)

[[4 5 6]
 [1 5 9]
 [7 2 9]]
Mean is:  5.333333333333333
Median is:  5.0


### Obtain each row in the second column of the first array.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr1 = np.array([arr, arr, arr, arr])
print(arr1)
print(arr1[:,1:2])

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[2]
 [2]
 [2]
 [2]]


### Convert Numeric entries(columns) of Iris.csv to Mean Centered Version

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
data=pd.read_csv('drive/MyDrive/Iris.csv')

In [ ]:
datam = data.iloc[:,:]
datam.mean()

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

### Study about numpy array attributes and implement it on the first matrix.

In [ ]:
print(arr1)

arr1.shape

brr = arr1.shape = (10,2)
print(brr)

[[1 2]
 [3 4]
 [5 1]
 [2 3]
 [4 5]
 [1 2]
 [3 4]
 [5 1]
 [2 3]
 [4 5]]
(10, 2)
