Linear Regression using PyTorch : 

In [1]:
import numpy as np
import torch

In [2]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [5]:
from torch.utils.data import TensorDataset

In [6]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [7]:
from torch.utils.data import DataLoader

In [8]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [9]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 87., 134.,  58.],
        [ 73.,  67.,  43.],
        [ 69.,  96.,  70.],
        [ 91.,  88.,  64.],
        [102.,  43.,  37.]])
tensor([[119., 133.],
        [ 56.,  70.],
        [103., 119.],
        [ 81., 101.],
        [ 22.,  37.]])


nn.Linear : 

In [10]:
import torch.nn as nn

In [11]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.3795,  0.4199, -0.0737],
        [-0.5392, -0.1629,  0.4797]], requires_grad=True)
Parameter containing:
tensor([-0.1403, -0.4692], requires_grad=True)


In [12]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3795,  0.4199, -0.0737],
         [-0.5392, -0.1629,  0.4797]], requires_grad=True),
 Parameter containing:
 tensor([-0.1403, -0.4692], requires_grad=True)]

In [13]:
preds = model(inputs)
preds

tensor([[ 52.5292, -30.1221],
        [ 66.6312, -33.1763],
        [ 84.8710, -41.3915],
        [ 53.8988, -44.7278],
        [ 61.1995, -19.7386]], grad_fn=<AddmmBackward0>)

Loss Functions : 

In [14]:
import torch.nn.functional as F


In [15]:
loss_fn = F.mse_loss


In [16]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(8851.6064, grad_fn=<MseLossBackward0>)


Optimizer : 

In [17]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)


Train for multiple epochs : 

In [18]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [19]:
fit(100, model, loss_fn, opt, train_dl)


Epoch [10/100], Loss: 572.7621
Epoch [20/100], Loss: 297.3408
Epoch [30/100], Loss: 260.1503
Epoch [40/100], Loss: 231.3232
Epoch [50/100], Loss: 205.9713
Epoch [60/100], Loss: 183.6058
Epoch [70/100], Loss: 163.8694
Epoch [80/100], Loss: 146.4492
Epoch [90/100], Loss: 131.0694
Epoch [100/100], Loss: 117.4873


In [20]:
prediction = model(inputs)
prediction

tensor([[ 61.5248,  72.2245],
        [ 80.8035, 102.2665],
        [114.8757, 126.2471],
        [ 46.1203,  48.6290],
        [ 84.8392, 115.0462]], grad_fn=<AddmmBackward0>)

In [21]:
targets


tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [22]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[58.7750, 70.3882]], grad_fn=<AddmmBackward0>)