In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

iris = datasets.load_iris()

In [2]:
print("Features: ", iris.feature_names)
print("Labels: ", iris.target_names)
iris.data.shape


Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']


(150, 4)

In [3]:
print("Features: ", iris.feature_names)
print("Labels: ", iris.target_names)
iris.data.shape

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']


(150, 4)

In [4]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(iris.data,iris.target, test_size = 0.30, random_state = 76)

In [5]:
import numpy as np
gnb = GaussianNB() 
gnb.fit(data_train, target_train) 
target_pred = gnb.predict(data_test)

In [6]:
from sklearn import metrics 
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.9777777777777777


In [8]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[19,  0,  0],
       [ 0, 12,  1],
       [ 0,  0, 13]], dtype=int64)

In [9]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1.         1.         0.92857143]
recall: [1.         0.92307692 1.        ]


In [10]:
#EXCERCISE : 

In [11]:
#TASK 1 : Try the algo on Dataset2 - OneHotEncoding of features: and Train test Division 75%-25%

In [12]:
import numpy as np 
import pandas as pd
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [13]:
dataset = pd.read_csv('E:\LABS\ML2\LAB03\Dataset2.csv')
print("\n\nData: \n",dataset)



Data: 
    Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N


In [14]:
data= pd.get_dummies(dataset,columns=['Outlook','Temp','Humidity','Wind','Class'])
data= data.drop(['Class_N'],axis=1)
print("One Hot Encoder:\n\n",data)

One Hot Encoder:

     Outlook_O  Outlook_R  Outlook_S  Temp_C  Temp_H  Temp_M  Humidity_High  \
0           0          1          0       0       1       0              0   
1           0          1          0       0       1       0              1   
2           1          0          0       0       1       0              0   
3           0          0          1       0       0       1              0   
4           0          0          1       0       0       1              0   
5           0          0          1       0       0       1              0   
6           1          0          0       1       0       0              0   
7           0          1          0       1       0       0              0   
8           0          1          0       1       0       0              0   
9           0          0          1       0       0       1              1   
10          0          1          0       0       0       1              1   
11          1          0          0       0  

In [15]:
#train-test split data 75%-25%

In [16]:
X= data.iloc[:,:-1]
Y= data.iloc[:,-1]
data_train, data_test, target_train, target_test = train_test_split(X, Y, test_size = 0.25, random_state = 76)

In [17]:
model = GaussianNB()

#Train the model using the training sets
model.fit(data_train, target_train)

#Predict the response for test dataset
target_pred =model.predict(data_test)

In [18]:
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.75


In [19]:
confusion_matrix(target_test, target_pred)

array([[1, 0],
       [1, 2]], dtype=int64)

In [20]:
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print(f'precision: {precision}')
print(f'recall: {recall}')

precision: [0.5 1. ]
recall: [1.         0.66666667]


In [21]:
#Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Normal’, and Wind = ’False’?
output1= model.predict([[0,1,0,0,0,1,0,0,1,1,0]])
print(f'Play: {output1}')
#Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’, and Wind = ’True'
output2= model.predict([[0,0,1,1,0,0,1,0,0,0,1]])
print(f'Play: {output2}')

Play: [0]
Play: [1]


In [22]:
#Task 2: Apply algorithm on wine dataset - LabelEncoding of features: and Train test Division 80%-20%

In [23]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
wine= datasets.load_wine()

In [24]:
print("Features: ", wine.feature_names)
# print the label type of wine(class_0, class_1, class_2)
print("Labels: ", wine.target_names)
# print data(feature)shape & target shape
print("\nData Shape: ",wine.data.shape)
print("\nTarget Shape:",wine.target.shape)

Features:  ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Labels:  ['class_0' 'class_1' 'class_2']

Data Shape:  (178, 13)

Target Shape: (178,)


In [25]:
data_train, data_test, target_train, target_test = train_test_split(X, Y, test_size = 0.20, random_state = 76)

In [26]:
gnb= GaussianNB()
model.fit(data_train, target_train)
target_pred= model.predict(data_test)

In [27]:
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))
confusion_matrix(target_test, target_pred)

Accuracy: 0.6666666666666666


array([[1, 0],
       [1, 1]], dtype=int64)

In [28]:
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)

print(f'precision: {precision}')
print(f'recall: {recall}')

precision: [0.5 1. ]
recall: [1.  0.5]
